GET http://localhost:3000/subscribers/

###

GET http://localhost:3000/subscribers/63173c0e000d470e86f9f676

### 

POST http://localhost:3000/subscribers/
Content-Type: application/json

{
   "name":"Matt Jefferson",
    "subscribedToChannel": "WebDevSimplified"
}